/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.market;


import java.math.BigInteger;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.RSAPublicKeySpec;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Arrays;
import javax.swing.JOptionPane;
/**
 *
 * @author ZZ
 */
public class Thanhtoan extends javax.swing.JFrame {
    static info info;
    private theXP theXP;
    String otp;
    BigInteger modulusPubkey,exponentPubkey ;
    int totalmoney;
    int sodiem = 0 ;
    String name_cus, time, date, name_drink, name_mov;
    int id_mov, ticket, price, pops,drinks,  point, total;
     
    public Thanhtoan(String name_cus1, String name_mov1, String time1, String date1, String name_drink1, int id_mov1, int ticket1, int price1, int pops1, int drinks1, int point1, int total1) {
//        this.theXP = CinemaForm.theXP;
        initComponents();
        totalmoney = total1;
        info = new info();
//        lbTotal.setText(""+totalmoney);
        name_cus = name_cus1;
        name_mov = name_mov1;
        date = date1;
        time = time1;
        name_drink = name_drink1;
        id_mov = id_mov1;
        ticket = ticket1;
        price = price1;
        pops = pops1;
        drinks = drinks1;
        point = point1;
        total = total1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JButton();
        txt_pin = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txt_OTP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_checkOTP = new javax.swing.JTextField();
        btn_otp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_otp1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel2.setText("Tổng  hóa đơn:");

        jLabel3.setText("Nhập mã PIN:");

        btn_ThanhToan.setBackground(new java.awt.Color(153, 153, 255));
        btn_ThanhToan.setText("Thanh toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        txt_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pinActionPerformed(evt);
            }
        });

        jLabel4.setText("VND");

        txt_OTP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_OTP.setText("áda");

        jLabel6.setText("Nhập OTP:");

        txt_checkOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_checkOTPActionPerformed(evt);
            }
        });

        btn_otp.setBackground(new java.awt.Color(153, 153, 255));
        btn_otp.setText("Lấy OTP");
        btn_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_otpActionPerformed(evt);
            }
        });

        jLabel5.setText("000");

        jPanel1.setBackground(new java.awt.Color(97, 218, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thanh toán");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 30));

        jLabel7.setText("Điểm tích lũy:");

        jLabel8.setText("000");

        btn_otp1.setBackground(new java.awt.Color(153, 153, 255));
        btn_otp1.setText("Sử dụng");
        btn_otp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_otp1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Thành tiền:");

        jLabel10.setText("000");

        jLabel11.setText("VND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_otp))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_checkOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btn_otp1)))
                    .addComponent(txt_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThanhToan))
                .addGap(43, 124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_otp1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_otp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_checkOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_ThanhToan)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        String pin = Arrays.toString(txt_pin.getPassword());
        String st;
        String checkotp = txt_checkOTP.getText();
        System.out.print(checkotp);
        if(checkotp.equals(otp) != true){
            JOptionPane.showMessageDialog(this, "OTP không đúng.");
        }else{
            byte[] cmdcreateSig = {(byte) 0xA0, (byte) 0x16, (byte) 0x01, (byte) 0x00};
            if (info.getRank() == "Thường"){
                sodiem = Math.round(totalmoney/20);
                st = Integer.toHexString(sodiem);
            }
            else{
                sodiem = Math.round(totalmoney/10);
                st = Integer.toHexString(sodiem);
            }
            short verifylen=0;
            if(Integer.valueOf(sodiem)<= 255){
                verifylen = 7;
            }else if(Integer.valueOf(sodiem)<= 4095){
                verifylen = 9;
            }else{
                verifylen = 10;
            }
            System.out.println(st);
            String arraysend= checkotp.concat(pin);
            theXP.sendAPDUtoApplet(cmdcreateSig,arraysend.getBytes());
            byte[] aa = theXP.resAPDU.getData();
            if(aa.length ==1|| theXP.resAPDU.getSW1()!= 0x90){
                JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Mã PIN không đúng");
                txt_OTP.setText("OTP hết hạn.");
                txt_checkOTP.setText("");
            }else{
                byte[] input  = arraysend.getBytes();
                String resCheck = String.format("%x", new BigInteger(1, aa));
                boolean verifyCheck = true;
              
                try {
                    verifyCheck = Verify_Digital_Signature(input,resCheck.getBytes());
                } catch (Exception ex) {
                }
                if(verifyCheck)
                {
                byte[] cmdverify = {(byte) 0xA0, (byte) 0x16, (byte) 0x02, (byte) 0x00};
                byte[] verify = new byte[7];
                if(verifylen == 7){
                    byte[] b = checkotp.getBytes();
                    System.arraycopy(b, (short)0, verify, (short)0, b.length);
                    verify[6]= Byte.valueOf(st,16);
                }
                if(verifylen == 9){
                    verify = new byte[verifylen];
                    byte[] b = checkotp.getBytes();
                    System.arraycopy(b, (short)0, verify, (short)0, b.length);
                    String[] tach = st.split("",3);
                    verify[6] = Byte.valueOf(tach[0],16);
                    verify[7] = Byte.valueOf(tach[1],16);
                    verify[8] = Byte.valueOf(tach[2],16);
                }
                if(verifylen == 10){
                    verify = new byte[verifylen];
                    byte[] b = checkotp.getBytes();
                    System.arraycopy(b, (short)0, verify, (short)0, b.length);
                    String[] tach = st.split("",4);
                    verify[6] = Byte.valueOf(tach[0],16);
                    verify[7] = Byte.valueOf(tach[1],16);
                    verify[8] = Byte.valueOf(tach[2],16);
                    verify[9] = Byte.valueOf(tach[3],16);
                }
                theXP.sendAPDUtoApplet(cmdverify, verify);
                byte[] res = theXP.resAPDU.getData();
                if(res[0] == 0x00){
                    JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Xác thực lỗi");
                    txt_OTP.setText("OTP hết hạn.");
                    txt_checkOTP.setText("");
                }else if (res[0] == 0x01){
                    JOptionPane.showMessageDialog(this, "Giao dịch thành công.");
                    try{
                        Connection con;
                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root","");
                        PreparedStatement ps = null;
                        ps = con.prepareStatement("insert into bill (name_customer,id_movies,time,ticket,pops,drinks,point,total) values(?,?,?,?,?,?,?,?)");
                        ps.setString(1, name_cus);
                        ps.setInt(2, id_mov);
                        ps.setString(3, time);
                        ps.setInt(4, ticket);
                        ps.setInt(5, pops);
                        ps.setInt(6, drinks);
                        ps.setInt(7, point);
                        ps.setInt(8, totalmoney);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Thêm thành công");
//                        HoaDon hoadon = new HoaDon(name_cus, name_mov, time, date, name_drink, id_mov, ticket, price, pops, drinks, point,totalmoney);
//                        hoadon.setVisible(true);
//                        hoadon.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        this.dispose();
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    }
                    setVisible(false);
                }else if(res[0] == 0x02){
                    JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Số tiền giao dịch vượt tối đa");
                    txt_OTP.setText("OTP hết hạn.");
                    txt_checkOTP.setText("");
                }
                }else
                {
                     JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Xác thực lỗi");
                    txt_OTP.setText("OTP hết hạn.");
                    txt_checkOTP.setText("");
                }
            }
        }
    }//GEN-LAST:event_btn_ThanhToanActionPerformed
 public boolean Verify_Digital_Signature(byte[] input,byte[] signatureToVerify) throws Exception{
         byte[] getModulusPubkey = {(byte) 0xA0, (byte) 0x22, (byte) 0x01, (byte) 0x01};
          theXP.sendAPDUtoApplet(getModulusPubkey);
          BigInteger resModulusPubkey = new BigInteger(1, theXP.resAPDU.getData());
          byte[] getExponentPubkey = {(byte) 0xA0, (byte) 0x22, (byte) 0x02, (byte) 0x01};
          theXP.sendAPDUtoApplet(getExponentPubkey);
          BigInteger resExponentPubkey = new BigInteger(1, theXP.resAPDU.getData());
          
        modulusPubkey = resModulusPubkey;
        exponentPubkey = resExponentPubkey;
        System.out.println("pubkey: "+modulusPubkey + " / "+exponentPubkey );
       
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        RSAPublicKeySpec pubKeySpec = new RSAPublicKeySpec(modulusPubkey, exponentPubkey);
        PublicKey key = (RSAPublicKey) keyFactory.generatePublic(pubKeySpec);
        
        Signature signature = Signature.getInstance("MD5WithRSA");
        signature.initVerify(key);
        signature.update(input);
        return signature.verify(signatureToVerify);
    }
    private void txt_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinActionPerformed

    private void btn_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_otpActionPerformed
        byte[] cmdOTP = {(byte) 0xA0, (byte) 0x16, (byte) 0x00, (byte) 0x00};
        theXP.sendAPDUtoApplet(cmdOTP);
        byte[] a = theXP.resAPDU.getData();
        otp = "";
        for (int i = 0; i < a.length; i++) {
            otp += theXP.byteToHex(a[i]);
        }
        txt_OTP.setText(otp);
    }//GEN-LAST:event_btn_otpActionPerformed

    private void btn_otp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_otp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_otp1ActionPerformed

    private void txt_checkOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_checkOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_checkOTPActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_otp;
    private javax.swing.JButton btn_otp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_OTP;
    private javax.swing.JTextField txt_checkOTP;
    private javax.swing.JPasswordField txt_pin;
    // End of variables declaration//GEN-END:variables
}
