/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nghiem Quynh
 */
public class InfoForm extends javax.swing.JFrame {

    static info info;
    static theXP theXP;
    private Boolean input = false;
    private boolean cardready = false;
    private boolean connected = false;
    public byte[] rsaPubKey = new byte[128];
    String ht;
    int sd;

    /**
     * Creates new form InfoForm
     */
    public InfoForm() {
        info = new info();
        theXP = new theXP();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setImage(byte[] img) {
        if (img == null) {
            return;
        }
        byte[] cmd = {(byte) 0xA0, (byte) 0x12, (byte) 0x01, (byte) 0x00};
        theXP.sendAPDUtoApplet(cmd);
        int sendlen = img.length;
        System.out.println("ảnh gửi:" + img);
        byte[] cmnd = {(byte) 0xA0, (byte) 0x12, (byte) 0x02, (byte) 0x00};
        int pointer = 0;
        byte[] temp = new byte[255];
        int datalen = 255;
        while (sendlen > 0) {
            System.arraycopy(img, pointer, temp, 0, datalen);
            theXP.sendAPDUtoApplet(cmnd, temp);
            pointer += 255;
            sendlen -= 255;
            if (sendlen < 255) {
                datalen = sendlen;
            }
        }
    }

    private void getImage(byte[] img) {
        if (img == null) {
            return;
        }
        try {
            byte[] cmd = {(byte) 0xA0, (byte) 0x13, (byte) 0x01, (byte) 0x00};
            theXP.sendAPDUtoApplet(cmd);
            int sendlen = img.length;
            byte[] cmnd = {(byte) 0xA0, (byte) 0x13, (byte) 0x02, (byte) 0x00};
            byte[] resimg = new byte[sendlen];
            int pointer = 0;
            int datalen = 255;
            while (sendlen > 0) {
                theXP.sendAPDUtoApplet(cmnd);
                byte[] temp = theXP.resAPDU.getData();
                System.arraycopy(temp, 0, resimg, pointer, datalen);
                pointer += 255;
                sendlen -= 255;
                if (sendlen < 255) {
                    datalen = sendlen;
                }
            }
            System.out.println("ảnh res:" + resimg);
            ByteArrayInputStream bais = new ByteArrayInputStream(resimg);
            BufferedImage b;
            b = ImageIO.read(bais);
            ImageIcon icon = new ImageIcon(b.getScaledInstance(anhthe.getWidth(), anhthe.getHeight(), Image.SCALE_SMOOTH));
            icon.getImage();
            anhthe.setIcon(icon);
        } catch (IOException ex) {

        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        anhthe = new javax.swing.JLabel();
        Btn_thayanh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_sodiem1 = new javax.swing.JLabel();
        btn_changePIN = new javax.swing.JButton();
        btn_capnhat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pin = new javax.swing.JPasswordField();
        Btn_Xemtt = new javax.swing.JButton();
        txt_sodiem2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin khách hàng");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        anhthe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Btn_thayanh.setBackground(new java.awt.Color(51, 204, 0));
        Btn_thayanh.setText("Thay ảnh");
        Btn_thayanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_thayanhActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Họ tên:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("SĐT:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Khách hàng:");

        txt_hoten.setText("null");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CMND:");

        txt_sodiem1.setText("0");

        btn_changePIN.setText("Thay đổi mã PIN");
        btn_changePIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changePINActionPerformed(evt);
            }
        });

        btn_capnhat.setText("Đổi thông tin");
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        jLabel4.setText("null");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel3.setText("Nhập mã PIN:");

        txt_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pinActionPerformed(evt);
            }
        });

        Btn_Xemtt.setBackground(new java.awt.Color(51, 204, 0));
        Btn_Xemtt.setText("Enter");
        Btn_Xemtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XemttActionPerformed(evt);
            }
        });

        txt_sodiem2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Btn_Xemtt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_changePIN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anhthe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Btn_thayanh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sodiem1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txt_sodiem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sodiem2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_sodiem1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)))
                    .addComponent(anhthe, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(Btn_thayanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Xemtt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_changePIN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_thayanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_thayanhActionPerformed
        if (connected == true && cardready == true) {
            JFileChooser fc = new JFileChooser();
            int returnValue = fc.showOpenDialog(this);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                BufferedImage bimage;
                try {
                    bimage = ImageIO.read(file);
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageIO.write(bimage, "jpg", baos);
                    byte[] img = baos.toByteArray();
                    setImage(img);
                    getImage(img);
                    info.setAvatar(img);
                    JOptionPane.showMessageDialog(this, "Thay ảnh thành công.");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        } else
            JOptionPane.showMessageDialog(null, "Chưa connect thẻ.");
    }//GEN-LAST:event_Btn_thayanhActionPerformed

    private void btn_changePINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changePINActionPerformed
        if (theXP.connectApplet() == true) {
            txt_hoten.setText("");
            txt_sodiem2.setText("");
            txt_sodiem1.setText("");
            txt_pin.setText("");
            updatePIN updatepin = new updatePIN();
            updatepin.setVisible(true);
            updatepin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else
            JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_btn_changePINActionPerformed

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
            txt_hoten.setText("");
            txt_sodiem2.setText("");
            txt_sodiem1.setText("");
            txt_pin.setText("");
            updateInfoForm updateinfo = new updateInfoForm(txt_hoten.getText(),txt_sodiem2.getText());
            updateinfo.setVisible(true);
            updateinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_btn_capnhatActionPerformed

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void txt_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinActionPerformed

    private void Btn_XemttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XemttActionPerformed
        if(theXP.connectApplet() == true){
            txt_hoten.setText("");
            txt_sodiem2.setText("");
            txt_sodiem1.setText("");
            txt_pin.setText("");
            String pin = Arrays.toString(txt_pin.getPassword());
            System.out.println("pass: " + pin);
            if(check_pin(pin) == 0) JOptionPane.showMessageDialog(null,"Mã PIN sai. Vui lòng nhập lại.");
            else if (check_pin(pin) == 1){
                cardready =true;
              
                byte[] cmd = {(byte) 0xA0, (byte) 0x11, (byte) 0x00, (byte) 0x00};
                byte[] data= {0};
                setCommandAPDU(cmd,(byte)0, data, (byte)0);//hien thi apdu cmd len GUI
                theXP.sendAPDUtoApplet(cmd);
                byte[] dataRes = theXP.resAPDU.getData();
                int le = theXP.resAPDU.getNr();
                setResponseAPDU(dataRes, (byte)le);//hien thi du lieu phan hoi tu applet
                String tach = new String(dataRes) ;
                //System.out.print("a:"+tach);
                String[] a = tach.split(":");
                String st = a[0];
                ht = a[1];
                String sdt = a[2];
                
//                txt_sothe.setText(st);
                txt_hoten.setText(ht);
//                txt_ngaysinh.setText(ns);
                txt_sodiem2.setText(sdt);
                txt_sodiem1.setText(st);
                 getImage(info.getAvatar());
                byte[] cmd1 = {(byte) 0xA0, (byte) 0x21, (byte) 0x00, (byte) 0x00};
                theXP.sendAPDUtoApplet(cmd1);
                byte[] b = theXP.resAPDU.getData();
                String sodu = "";
                for (int i = 0; i < b.length; i++) {
                    sodu += theXP.byteToHex(b[i]);
                }
                sd = Integer.valueOf(sodu,16).intValue();
                if (sd >=10){
                    info.setRank("VIP");
                }
                System.out.println("avatar" + info.getAvatar());
//                setImage(info.getAvatar());
//                getImage(info.getAvatar());
//                txt_xephang.setText(info.getRank());
//                txt_sodiem.setText(""+sd);
            }else JOptionPane.showMessageDialog(null, "Bạn đã nhập sai quá số lần cho phép. Thẻ đã bị khóa!");
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_Btn_XemttActionPerformed

    public int check_pin(String pin) {
        short lc = (short) pin.length(); //do dai du lieu gui vao applet
        short le = 1;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0xA0, (byte) 0x19, (byte) 0x00, (byte) 0x00};
        byte[] data = pin.getBytes();
        setCommandAPDU(cmd, (byte) lc, data, (byte) le);
        theXP.sendAPDUtoApplet(cmd, data);
        byte[] dataRes = theXP.resAPDU.getData();
        int lenRes = theXP.resAPDU.getNr();
        setResponseAPDU(dataRes, (byte) lenRes);
        //String a = new String(dataRes);
        if (dataRes[0] == (byte) 0x01) {//đúng mã PIN
            return 1;
        } else if (dataRes[0] == (byte) 0x00) {
            return 0;
        } else {
            return 2;
        }
    }

    public void setCommandAPDU(byte[] cmnds, byte lc, byte[] data, byte le) {
//        txt_cla.setText(theXP.byteToHex(cmnds[0]));
//        txt_ins.setText(theXP.byteToHex(cmnds[1]));
//        txt_p1.setText(theXP.byteToHex(cmnds[2]));
//        txt_p2.setText(theXP.byteToHex(cmnds[3]));
//        txt_lc.setText(theXP.byteToHex(lc));
//        //data
//        String temp = "";
//        for (int i = 0; i < data.length; i++) {
//            temp += theXP.byteToHex(data[i]);
//            temp += " ";
//        }
//        txt_cmd.setText(temp);
//        txt_le.setText(theXP.byteToHex(le));
    }

    //hien thi apdu phan hoi len
    public void setResponseAPDU(byte[] datares, short le) {
//        int status1 = theXP.resAPDU.getSW1();
//        int status2 = theXP.resAPDU.getSW2();
//        txt_sw1.setText(theXP.shorttoHex((short)status1));
//        txt_sw2.setText(theXP.shorttoHex((short)status2));
//        if (le != 0 && datares.length != 0) {
//            //hien thi du lieu ra
//            String temp = "";
//            for (int i = 0; i < datares.length; i++) {
//                temp += theXP.byteToHex(datares[i]);
//                temp += " ";
//            }
//            txt_respon.setText(temp);
//        }
    }
    static void setData(info in) {
        InfoForm infoForm = new InfoForm();
        infoForm.setVisible(true);
        infoForm.info = in;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new InfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Xemtt;
    private javax.swing.JButton Btn_thayanh;
    private javax.swing.JLabel anhthe;
    private javax.swing.JButton btn_capnhat;
    private javax.swing.JButton btn_changePIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel txt_hoten;
    private javax.swing.JPasswordField txt_pin;
    private javax.swing.JLabel txt_sodiem1;
    private javax.swing.JLabel txt_sodiem2;
    // End of variables declaration//GEN-END:variables
}
